@startuml
'https://plantuml.com/state-diagram

scale 480 width
[*] --> ItemList

state ItemList
ItemList: Item ID to load
ItemList -down[#red]-> Loading : ItemClicked(itemId)

state Loading {
    state Status <<choice>>
}
Status -[#blue]-> Error : onError
Status -left[#blue]-> Content : onContent

state Error
Error -[#red]-> Loading : Retry
Error -[#red]-> Terminated : Exit

state Content
Content -up[#red]-> ItemList: Back

state Terminated
@enduml